---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

inputs:
  - name: create-vault

run:
  path: create-vault/ci/tasks/delete-vault-deployment.sh