resources:
- name: create-vault
  type: git
  source:
    branch: master
    uri: https://github.com/ECSTeam/create-vault
    username: ((git-srv-user))
    password: ((git-srv-password))

jobs:
- name: test-create-vault
  plan:
  - aggregate:
    - get: create-vault
      trigger: false
  - task: create
    file: create-vault/ci/tasks/create-vault-test.yml
    params:
      BOSH_DIRECTOR: {{bosh-director}}
      BOSH_CA: ((bosh-ca))
      BOSH_ADMIN_PASSWORD: ((admin-password))